services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    restart: unless-stopped
    volumes:
      - ./.sqlserver:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - tangelo

  bot:
    image: ghcr.io/stephenmelnicki/tangelo/bot
    container_name: bot
    restart: unless-stopped
    build:
      context: ./src/Tangelo.Bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - tangelo

  web:
    image: ghcr.io/stephenmelnicki/tangelo/web
    container_name: web
    restart: unless-stopped
    build:
      context: ./src/Tangelo.Web
    networks:
      - tangelo

networks:
  tangelo:
