services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    restart: unless-stopped
    volumes:
      - ./.sqlserver:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - tangelo

  www:
    image: ghcr.io/stephenmelnicki/tangelo
    container_name: www
    restart: unless-stopped
    build:
      context: ./src/Tangelo
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - tangelo

  proxy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - sqlserver
      - www
    networks:
      - tangelo

volumes:
  caddy_data:
  caddy_config:


networks:
  tangelo:
