name: deploy-bot

on:
  push:
    branches: [main]
    paths:
        - "bot/**"
      
  pull_request:
    branches: [main]
    paths:
        - "bot/**"

defaults:
  run:
    working-directory: bot


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "tangelo-bot"
          entrypoint: "bot/mod.ts"
